baseURL = "http://docs.virtdata.io/"
languageCode = "en-us"
title = "VirtualDataSet"
theme = "hugo-material-docs"
metadataformat = "yaml"
canonifyurls = true

[params]
	# General information
	# author = "Jonathan Shook"
	description = "VirtualDataSet Docs"
	copyright = "APL 2.0"

	# Repository
	# provider = "GitHub"
	# repo_url = "https://github.com/virtdata/

	# version = "1.0"
	logo = "images/virtdata_128.png"
	favicon = "/images/engineblock_32.png"

	# permalink = "#"

[params.palette]
    primary = "grey"
    accent  = "teal"

[params.font]
    text = "Roboto"
    code = "Roboto Mono"

[social]
	github  = "virtualdataset/metagen-java"

[blackfriday]
	smartypants	= true
	fractions = true
	smartDashes = true
	plainIDAnchors = true

[[menu.main]]
	name   = "Introduction"
	url    = "/"
	weight = 10

[[menu.main]]
	name   = "Concepts"
	url    = "/concepts"
	weight = 30

[[menu.main]]
	name   = "Modeling Datasets"
	url    = "/modeling_datasets"
	weight = 40

[[menu.main]]
    name   = "Syntax Reference"
    url    = "/syntax"
    weight = 50

[[menu.main]]
	name   = "Function Reference"
	url    = "/functions"
	weight = 60
	
#[[menu.main]]
#    name   = "Design Sketches"
#    url    = "designsketches/"
#    weight = 200


