baseURL = "http://docs.virtdata.io/"
languageCode = "en-us"
title = "VirtualDataSet"
theme = "hugo-material-docs"
metadataformat = "yaml"
canonifyurls = true

[params]
	# General information
	# author = "Jonathan Shook"
	description = "VirtualDataSet Docs"
	copyright = "APL 2.0"

	# Repository
	# provider = "GitHub"
	# repo_url = "https://github.com/virtdata/

	# version = "1.0"
	logo = "images/engineblock_128.png"
	favicon = "/images/engineblock_32.png"

	# permalink = "#"

[params.palette]
    primary = "grey"
    accent  = "teal"

[params.font]
    text = "Roboto"
    code = "Roboto Mono"

[social]
	github  = "virtualdataset/metagen-java"

[blackfriday]
	smartypants	= true
	fractions = true
	smartDashes = true
	plainIDAnchors = true

[[menu.main]]
	name   = "VirtData.io"
	url    = "/"
	weight = 10

[[menu.main]]
	name   = "Introduction"
	url    = "/intro"
	weight = 20

#[[menu.main]]
#    name   = "Design Sketches"
#    url    = "designsketches/"
#    weight = 200


